# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Fedora - Slimbook Theme"
license = "MIT"
licenselink = "https://github.com/slimbook-team/fedora-slimbook/blob/master/LICENSE"
description = ""
homepage = "http://slimbook.com/"
tags = []
features = []
min_version = "0.114.1"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

